### ISSUE TITLE
Trying the Jas Skin

### ISSUE THREAD

**Issue by gand07** [bellrichm/weewx-jas#119]
Hi
Just installed  version 1.0.1 on Ubuntu 20.04 and WeeWx 4.10.2. I'm using NGINX web server.

After 5 minutes a folder  named data is created in the public_html directory and only that one, no additional files. The files in the data directory is updated every 5 minutes.

No error in the syslog.

What have I missed?

Gert

**Comment by bellrichm** [comment]
Did you make any modifications to weewx.conf? What version of WeeWX? What version of python? 
The next step is to set debug = 2 and attach the log. In the meantime I’ll do a clean install and see if I can recreate.

**Comment by gand07** [comment]
Hi
I added
[[jas]]
        skin = jas
        enable = true
		unit_system = METRICWX
unit_system was needed , otherwise I got::
ERROR weewx.reportengine:         ****  KeyError: 'unit_system'

WeeWx Version 4.q0.2
Ubuntu version:20.04.6 LTS
Phyton version:3.8.10

I have tried debug 1 to 3 and no information in syslog and no errors.

I have attached a screenshot of directory and files in the root directory. Do I miss anything here?

gert

**Comment by gand07** [comment]
Here are the screenshots and a how the web page looks like

![jas](https://github.com/bellrichm/weewx-jas/assets/47734099/c358267b-213c-4e5c-8aaf-5400aa726e53)
![jas1](https://github.com/bellrichm/weewx-jas/assets/47734099/df1cbe24-7985-4557-8246-f3560b63bef1)

**Comment by bellrichm** [comment]
> Hi I added [[jas]] skin = jas enable = true unit_system = METRICWX unit_system was needed , otherwise I got:: ERROR weewx.reportengine: **** KeyError: 'unit_system'
> 
> WeeWx Version 4.q0.2 Ubuntu version:20.04.6 LTS Phyton version:3.8.10
> 
> I have tried debug 1 to 3 and no information in syslog and no errors.
> 
> I have attached a screenshot of directory and files in the root directory. Do I miss anything here?
> 
> gert

Odd, that you had to add unit_system = , I don’t have that in my config. If you have no log, where are you seeing that error.

Why did you install from the master branch? That is not released code. You should install from https://github.com/bellrichm/weewx-jas/releases/tag/v1.0.0

Also, you really need to figure out where your logs are. It is close to impossible to get help without them.

**Comment by bellrichm** [comment]
> Here are the screenshots and a how the web page looks like
> 
> ![jas](https://user-images.githubusercontent.com/47734099/262489185-c358267b-213c-4e5c-8aaf-5400aa726e53.jpg) ![jas1](https://user-images.githubusercontent.com/47734099/262489187-df1cbe24-7985-4557-8246-f3560b63bef1.jpg)

Top level directory structure looks correct, it matters what is in the subdirectories.

**Comment by bellrichm** [comment]
Since you closed this, are you all set?

**Comment by gand07** [comment]
My fault, shouldn't be closed
I have a syslog file, but no errors from the skin except the one with the missing unit_system
I will uninstall the master version(my mistake) and install version 1.0.0
I will close this thread and open a new one if necessary with the correct version installed.
Gert

**Comment by gand07** [comment]
Closed
