### ISSUE TITLE
Times are shown in 12-hour format without AM/PM

### ISSUE THREAD

**Issue by gdt** [bellrichm/weewx-jas#13]
(As seen on the demo site, yesterday, solar radiation max at 01:15.)

I'd want 24-hour format anyway, but noticed this when looking at times to see if that was doable.  The graph x-axes are labeled in 24h time, so that's good.

**Comment by bellrichm** [comment]
Yup, date/time handling definitely needs work. I’ll use this issue to track it. 
But I think my next big feature is to enable updating charts via MQTT. I also want to move my external site to AWS, so it might be a bit.
rich

**Comment by bellrichm** [comment]
Default date/time format for min/max changed to 24 hr at commit f16a0d59ff731fa1e55b6e9196a75339eac3e568.
Still need to look at
- [ ] Current date/time
- [ ] xaxis
- [ ] tooltip

**Comment by bellrichm** [comment]
The following options have been added to configure date/time formatting.
```
    current_date_time = MM/DD/YYYY HH:mm:ss
    # chart formatting
    [[aggregate_interval_none]]
        tooltip_x              = HH:mm
        xaxis_label            = HH:mm    
        label                  = HH:mm   
    [[aggregate_interval_hour]]
        tooltip_x              = MM/DD HH:mm
        xaxis_label            = MM/DD
        label                  = MM/DD HH:mm 
    [[aggregate_interval_day]]
        tooltip_x              = MM/DD    
        xaxis_label            = MM/DD
        label                  = MM/DD
    [[aggregate_interval_week]] 
        tooltip_x              = MM/DD    
        xaxis_label            = MM/DD  
        label                  = MM/DD  
```
Documentation to come...

**Comment by bellrichm** [comment]
Wiki page created
https://github.com/bellrichm/weewx-jas/wiki/Localization
