### ISSUE TITLE
No data for Year/Month

### ISSUE THREAD

**Issue by bellrichm** [bellrichm/weewx-jas#135]
### Discussed in https://github.com/bellrichm/weewx-jas/discussions/134

<div type='discussions-op-text'>

<sup>Originally posted by **gand07** November 25, 2023</sup>
Hi
I'm running version 1.1.0 and I have a question about Year/month.

When I choose a Year and a Month, I have no data for that combination, except the combination for 2023/11.

You can see the site [here](https://argon1.billeder.de/#) 

Any ideas)
Gert</div>

**Comment by gand07** [comment]
Hi
Working perfect.
Thanks
Gert

**Comment by bellrichm** [comment]
Released in 1.1.1.
