### ISSUE TITLE
Missing year 2024

### ISSUE THREAD

**Issue by gand07** [bellrichm/weewx-jas#136]
Hi
I'm missing year 2024 in the Drop-Down list. See screenshot
Thanks for looking

<img width="940" alt="2024-01-02" src="https://github.com/bellrichm/weewx-jas/assets/47734099/e675b0b8-3742-4f55-a0d9-73efd780481c">

Gert

**Comment by bellrichm** [comment]
Thanks for reporting this. I’ve got a few things keeping me busy, so it might take a bit.

**Comment by bellrichm** [comment]
The array of years and months is only being generated at WeeWX startup and therefore did not update when the new year started.

A fix will be coming shortly. It will require a restart of WeeWX. If you want to work around the bug, just restart WeeWX now.
