### ISSUE TITLE
Blank Pages- No Data

### ISSUE THREAD

**Issue by gary-hammer** [bellrichm/weewx-jas#29]
I installed and configured the HTML_ROOT, MQTT info, ran weewx for a cycle.
Saw files output to the proper location. Page is blank except for the header (black bar with site name, refresh, day, week, etc)
How would I know the skin is actually reading the MQTT data?

Attaching a small log snip, sample of the loop and rec, the config I did.
[weewx-jas.txt](https://github.com/bellrichm/weewx-jas/files/9093357/weewx-jas.txt)

**Comment by bellrichm** [comment]
Thanks for giving it it try.  It is still pretty rough around the edges.  Getting documentation written is my current focus.

So, none of the pages show any charts? I'm fixing a bug that might cause it to be blank on initial load. What does your `pages` section look like?

In the next release a 'debug' page will be configured but disabled. You could add one now. It will show the MQTT data. Here is an example. The outTemp graph will use MQTT data and barometer will use archive data.
```
            [[[[pages]]]]
                [[[[[debug]]]]]
                    [[[[[[outTemp]]]]]]
                        series_type = mqtt
                    [[[[[[barometer]]]]]]
```

**Comment by gary-hammer** [comment]
My pages section is the default from install, changed nothing from default except the MQTT info.
There is nothing except the header bar.
I inserted the debug as shown and then `debug.navbarText` is added to the header but does nothing.

Files are created in the web directory, just no display is seen. current.js has values in it for example.
debug.js looks to be empty of values though.
I'm attaching both those with the extension changed to .txt for github.
[current.js.txt](https://github.com/bellrichm/weewx-jas/files/9100626/current.js.txt)
[debug.js.txt](https://github.com/bellrichm/weewx-jas/files/9100628/debug.js.txt)

**Comment by bellrichm** [comment]
At the moment I'm stumped. No sense in looking into MQTT if we can't get the archive data to display.
Are you running it directly from the filesysytem or via a web server? Can you try it the other way?
What happens if you go directly to pages/last24hours.html from the filesystem? Through a web server?
Could you attach the following:
pages/last24hours.html
charts/last24hours.js
data/last24hours.js
javascript/last24hours.js

**Comment by gary-hammer** [comment]
Well, it gets curiouser.
If I download the files you requested and open it with Chrome on my Windows machine, you get charts.
If I open the index from the web server using FF on Linux, I get quite odd results.
I'm attaching a zip with the files you asked for and screenshots of my filesystem browsing.
[gh-info.zip](https://github.com/bellrichm/weewx-jas/files/9105639/gh-info.zip)

**Comment by gary-hammer** [comment]
I run Apache.
It's on a test server, not accessable from outside.
Any test or info you'd like?

**Comment by bellrichm** [comment]
Thanks! Not sure what I am looking for. But lets see if this turns up anything
- Start FF
- Open Developer Tools (F12)
- Navigate to your website
- Select a different interval (week, month, etc.)
- Review the console for any errors (there will be some warnings from the radar URL)
- Review the network tab to see if there is anything 'interesting' (make sure **all**) is selected

Thanks again for your help.

**Comment by gary-hammer** [comment]
I think it would have to be the config of the webserver.
Referrer Policystrict-origin-when-cross-origin
I'll see if I can figure how to disable that.

![jas-01](https://user-images.githubusercontent.com/12861605/179419113-1052d63a-df98-4741-8794-ec28553008bd.png)
![jas-02](https://user-images.githubusercontent.com/12861605/179419114-963518f8-cd26-4333-9098-c42bb56991b5.png)

**Comment by gary-hammer** [comment]
This may or may not be helpful, it seems to present ways around CORS failures.

[https://spring.io/guides/gs/rest-service-cors/](url)

**Comment by bellrichm** [comment]
The favicon 404 is a bit of a red herring. I’m in the process of creating and shipping one. I also get this error.
Could you check that the skin has created the javascript/index.js and javascript/mqtt.js? Do you see other 404s?
If these files exist, what are the permissions? 
I have the same ‘Referrer Policy’ setting
The 404 does not feel like a CORS issue to me

**Comment by bellrichm** [comment]
I spun up a VM with apache. It loaded and displayed for me. 
One other possibility is that the generation of pages did not work, but I would I have expected some errors in the log.
I'll keep looking, but I'm running out of ideas.

**Comment by gary-hammer** [comment]
I'll send you a directory list of the output directories.

There are a number of .js files and a few html
Of course, you'd know if they are all there.

**Comment by bellrichm** [comment]
Thanks. For a default install, that all looks reasonable.
The 404 for the mqtt.js and index.js still puzzles me. I'm using a 'script' tag to get them... This error would definitely cause problems.
I've done a lot of cleanup since the last release. The favicon 404 should be fixed. By default the radar will be off. Net, the console should be a lot 'cleaner'.
I don't think this release will fix anything, but might make debugging easier. If you are still willing to help, I'll let you know when it's available (currently final test on my production server)

**Comment by gary-hammer** [comment]
Thanks Rich,

I'm ready, willing, and able.
Let me know.

**Comment by bellrichm** [comment]
Again, thanks.
New release, https://github.com/bellrichm/weewx-jas/releases/tag/v0.2.2-rc02
It would be best to:
- uninstall
- delete generated files
- cleanup weewx.conf

I’ll be interested in what this shows in the console and also the network tab.

**Comment by gary-hammer** [comment]
I'll get it installed tomorrow morning.

**Comment by gary-hammer** [comment]
Success!
Did the prep you suggested and have webpages.
No MQTT enabled, just the stock/default as installed.
Off to enable MQTT.

**Comment by gary-hammer** [comment]
With MQTT enabled, the current data text is updated properly.
I do see this in the console. No idea if it affects anything though as the overall webpage looks good.
`DevTools failed to load source map: Could not load content for http://lts.lan/jas/weather-icons/css/weather-icons.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

Now I need to see how to get the charts to update with MQTT.

Thanks Rich. Feel free to close this unless you need more info/testing.

**Comment by bellrichm** [comment]
Sorry, I just saw your last comment about MQTT. My guess is that the data in your  MQTT message does not match WeeWX observation names. If you enable the debug page it will show information about MQTT.  
```
            [[[[pages]]]]
                [[[[[debug]]]]]   
                    enable = true
                    [[[[[[debug]]]]]]   
                    [[[[[[current]]]]]]   
                    [[[[[[outTemp]]]]]]   
                        series_type = mqtt  
                    [[[[[[barometer]]]]]]

```
Note, I broke this is in 0.2.2-rc02.

Also thanks for being the only person, that I know of, that is crazy enough to try this. Your feedback is greatly appreciated. 
I’ll open  another issue to map MQTT names to WeeWX names. Since the original problem is ‘fixed’, I’ll close this one.

**Comment by bellrichm** [comment]
See issue #33

**Comment by gary-hammer** [comment]
All files are in the proper locations.
As other skins are fine from the location, I'm sure permissions are
correct. Meaning all I need do is to enable Seasons and the pages are
served.
I didn't notice favicon, I saw the CORS notice and the two .js files not
loading.
But then, the use of JavaScript isn't something I am familiar with.

**Comment by gary-hammer** [comment]
I could install the skin on my live server and use a subdirectory for its
output.
Then, you could do whatever you wanted access for.
Let me know.

**Comment by bellrichm** [comment]
I thought you got this working… If you are still having problems access to it live should help.

**Comment by gary-hammer** [comment]
Yes, I do have it working.
Sorry, I thought this was closed.

**Comment by bellrichm** [comment]
No problem. This is the second email I got from GitHub that referenced an old conversation. 
Sorry for any confusion.
