### ISSUE TITLE
Weather Icons Not Found

### ISSUE THREAD

**Issue by gary-hammer** [bellrichm/weewx-jas#36]
Not sure if this is a valid error, I've never seen icons and I'm not sure I want to.
In any event, when using dev tools in Chrome, I get this error on the network tab.
`DevTools failed to load source map: Could not load content for http://lts.lan/jas/weather-icons/css/weather-icons.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by gary-hammer** [comment]
BTW- MQTT is working well now with the fields addition.

**Comment by bellrichm** [comment]
The message from `Devtools` is because a file used to help debug is not found. This does not affect the site's functionality.
But I had been playing around with the icons. There should be a couple (rain/wind) showing in the forecast section. It appears that this is currently broken.
Thanks for catching this.

**Comment by bellrichm** [comment]
It looks like when the code was updated to dynamically update the forecast data it broke the displaying of icons for the temperature and wind data.
Need to change the code to something like this
```
        forecasts.forEach(function(forecast)
        {
            observationId = 'forecastObservation' + i;
            document.getElementById('forecastDate' + i).innerHTML = forecast['day']  + ' ' + forecast['date'];
            document.getElementById('forecastObservation' + i).innerHTML = forecast['observation'];
            document.getElementById('forecastTemp' + i).innerHTML = forecast['min_temp'] + ' | ' + forecast['max_temp'];
            document.getElementById('forecastRain' + i).innerHTML = forecast['rain'] + '%' + '<i class="wi wi-raindrop"></i>';
            document.getElementById('forecastWind' + i).innerHTML = forecast['min_wind'] + ' | ' + forecast['max_wind'] + ' mph';
            i += 1;
        });
```
Along with updating the data, need to add the icon, ` '<i class="wi wi-raindrop"></i>';`
