### ISSUE TITLE
Rain Not Shown As Text But Is Graphed

### ISSUE THREAD

**Issue by gary-hammer** [bellrichm/weewx-jas#37]
We've had rain today and the Rain Today is displaying 0.0 
I did see it flash 0.1 once as we were getting rain at the time.
I'd think the MQTT feed showed it for the short time, then it was replaced by the 0.0
If it were showing 0.1 it would have been an incorrect value anyway, as it had rained an extra 0.01" at the time.

**Comment by bellrichm** [comment]
Sorry, not quite following.
If you are saying that the 'current' conditions with MQTT enabled is not showing rain, I think the problem is that `rain` in the loop packet and therefore in the MQTT payload is incremental. I did a quick check and my loop has a `dayRain` observation.
I'll try to remember to look at this the next time there is rain here.

**Comment by gary-hammer** [comment]
Yes, though I did see an occasional value.

Not likely to be observed here again for a while, rain is scarce.

**Comment by gary-hammer** [comment]
Well, this is what I'm seeing now during a heavy rain.
![rain](https://user-images.githubusercontent.com/12861605/186964501-264b2ee5-e79b-4425-bb96-a6f606b74da9.png)

**Comment by gary-hammer** [comment]
I'm looking at the entire loop and do not see anything except dayRain_in to use, so I'll swap that for the rain value.

**Comment by gary-hammer** [comment]
Bingo! That solved it.

**Comment by gary-hammer** [comment]
Could we get 2 digit display on rain?
As in 0.74 vs 0.7

**Comment by bellrichm** [comment]
Interesting that you don’t see rain24 (or in your case rain24_in). I definitely saw it when I was recently experimenting with the simulator and weewx-mqtt.
I haven’t done any work on data formatting. I’ll probably open a separate issue and the close this. Is the number of decimal places in the MQTT message just 2?
I’m just finishing up support for two y-axis. Then I want to clean up the default charts.After that would probably be data formatting options.

**Comment by gary-hammer** [comment]
Sounds good to me.
I'll have to see what dayRain_in provides, but I'm thinking it is going to reset at 00:00 where rain24 would carry over for 24 hours.
It has stopped raining, so can't answer on the decimal places.

Have a good weekend, hopefully my Covid will test negative soon.
