### ISSUE TITLE
Configure formatting of data values

### ISSUE THREAD

**Issue by bellrichm** [bellrichm/weewx-jas#42]
See #37, #40

**Comment by bellrichm** [comment]
Since the MQTT data needs to be formatted, leveraging WeeWX `StringFormats` doesn't make much sense. It really needs to be done in javascript.

**Comment by bellrichm** [comment]
For charts, `valueFormatter` introduced in 5.3 will be leveraged. The default number of decimal points will be 2. Any chart can easily override this.
Will need to decide if predefined charts should override it.

**Comment by bellrichm** [comment]
@hoetzgit
I have created a [beta release](https://github.com/bellrichm/weewx-jas/releases/tag/v0.2.3-rc01) with this functionality. I added an option under the observation in the 'current' section. It looks something like this
```
            [[[[current]]]]
                observation = outTemp
                [[[[[observations]]]]]
                    [[[[[[heatindex]]]]]]   
                    [[[[[[windchill]]]]]]
                        max_decimals = 2   
                    [[[[[[dewpoint]]]]]]
                        max_decimals = 2   
                    [[[[[[outHumidity]]]]]]
```

**Comment by hoetzgit** [comment]
@bellrichm 
I have tested it with the following configuration. I noticed that sometimes it works for `outTemp `and sometimes not (see screenshots). It does not work for `barometer`/`windspeed`/`radiation `for example. I deleted the web directory before and it was recreated after the skin update. 
Have I configured incorrectly?

[website](https://jas.weiherhammer-wetter.de)

Many thanks and greetings
Henry

weewx.conf:

```
            [[[[current]]]]
                # The header observation is outTemp
                observation = outTemp
                [[[[[observations]]]]]
                    [[[[[[outTemp]]]]]]
                        max_decimals = 1
                    [[[[[[heatindex]]]]]]
                        max_decimals = 1
                    [[[[[[windchill]]]]]]
                        max_decimals = 1
                    [[[[[[dewpoint]]]]]]
                        max_decimals = 1
                    [[[[[[outHumidity]]]]]]
                        max_decimals = 0
                    [[[[[[barometer]]]]]]
                        max_decimals = 0
                        suffix = ($trend.barometer.formatted)
                    [[[[[[windSpeed]]]]]]
                        max_decimals = 0
                        suffix = $current.windDir.ordinal_compass ($current.windDir)
                    [[[[[[rainRate]]]]]]
                        max_decimals = 1
                    [[[[[[rain]]]]]]
                        max_decimals = 1
                        type = sum
                        mqtt = false
                    [[[[[[ET]]]]]]
                        max_decimals = 1
                        type = sum
                        mqtt = false
                    [[[[[[UV]]]]]]
                        max_decimals = 0
                    [[[[[[radiation]]]]]]
                        max_decimals = 0
```


![image](https://user-images.githubusercontent.com/41108116/188393960-4bfcafe4-a78e-48e2-94f7-a803c1d06e0f.png)

Short time after:

![image](https://user-images.githubusercontent.com/41108116/188394074-57e16975-c813-43c1-a95b-9c107c7058af.png)

**Comment by bellrichm** [comment]
Oops. 
The barometer, windSpeed, etc are due to a bug not handling a value of 0.
The outTemp is a special case (being the 'header').
I'll work on a fix.  Thanks for the help.

**Comment by bellrichm** [comment]
support for the configuring the header has been added via 
8a15deef064907f08f71e45f96956bbb353f4f08
for 'additional' information see
https://github.com/bellrichm/weewx-jas/wiki/Sections#header_max_decimals

**Comment by hoetzgit** [comment]
@bellrichm 

I have updated the skin and regenerated my html root. You can see the result on my [website](https://jas.weiherhammer-wetter.de) . On a first test the format was wrong again after an update.

I also observed that the weather forecast was blank after some time, but I need to look at that again carefully.

**Comment by hoetzgit** [comment]
@bellrichm 

Thank you very much, looks very good and works. Had first forgotten the parameter `header_max_decimals` and thought it does not work.

I noticed by chance that after some time the weather forecast was empty. But can not reproduce this and must continue to monitor this.

**Comment by bellrichm** [comment]
Thanks for letting me know!
Let me know if you find anything about the empty forecasts. I'll try to look at the code and see if I can see anything.
Off topic - I see that you translated the skin. Any feedback on that is welcome. I did not follow WeeWX best practices of using the english text as the key and wonder if that made it more difficult.
Also I see that the 'year to year' doesn't look quite right and the date format is wrong... It is easy to remove if you want.
