### ISSUE TITLE
Perform internationalization in javascript

### ISSUE THREAD

**Issue by bellrichm** [bellrichm/weewx-jas#62]
Not sure how feasible, but moving text lookup and date formatting into the javascript would allow changing the locale/language based on the browser locale or even user choice.
Note, the numerical formatting is already in the javascript. See #59 

- [x] Dates and time
- [x] Text translations
- [x] Using the browser to select the language needs to be configurable. The default should be to use the lang setting in weewx.conf
- [x] Need to set the html lang tag appropriately 
- [x] In the ‘current’ section need to translate current forecast from aeris.
- [x] Allow the user to select desired language.

**Comment by bellrichm** [comment]
Since a design point is to not require a web server, all locale data will need to be downloaded. Perhaps the main page could do it once and each iframe read it somehow

**Comment by bellrichm** [comment]
Things like WeeWX labrls are going to be a challenge because these are deeply embedded in the WeeWX architecture

**Comment by PRO-BROS** [comment]
I also faced a similar issue on my [site](https://prhocoding.com/) but thankfully I hire a developer which resolve that's issue.
