### ISSUE TITLE
MQTT Stopped Working In Webpage 0.2.3

### ISSUE THREAD

**Issue by gary-hammer** [bellrichm/weewx-jas#66]
Odd issue.
Was performing wonderfully, values updated, time stamp on the page updated with each MQTT packet..

Then, nothing.

The base pages are created, the info is kind of correct as of the creation date. Except the time and date below the current info is not changing it seems.

I have created a file with weewx debug info, that to me, shows no issue.
MQTT is absolutely there as it is the data source for the test server as well as showing on other skins for weewx.

It could be related to 0.2.3 as there are errors related to MQTT in the developer console.
Attaching file jas-mqtt.txt with info.

[jas-mqtt.txt](https://github.com/bellrichm/weewx-jas/files/9911051/jas-mqtt.txt)

**Comment by bellrichm** [comment]
At the moment I am puzzled. I’ll let you know what, if any, additional info I need.

**Comment by bellrichm** [comment]
Could you attach your `javascript/last24hours.js`?
Did it ever work at 0.2.3?
What if you refresh? Reload?

**Comment by gary-hammer** [comment]
I have refreshed, reloaded CTL-F5, Shift-F5, etc.
I have tried Chrome and Firefox.
Tried the tablet, a Chromebook, and my PC

I'm including the developer output log and the js you requested. Have to change from js to txt to upload.

It did work with 0.2.2, but the display of appTemp was bad as there was no formatting of the number available.

[jas-dev-log.log](https://github.com/bellrichm/weewx-jas/files/9914940/jas-dev-log.log)
[last24hours.txt](https://github.com/bellrichm/weewx-jas/files/9914948/last24hours.txt)

**Comment by bellrichm** [comment]
I’m a bit stumped. My plan is to ‘catch’ the error and write some info to the console.  Unfortunately this will be an iterative exercise. I'll let you know when I have a release ready. 
Thanks for your help. rich

**Comment by gary-hammer** [comment]
Sounds good.
At your service.

**Comment by bellrichm** [comment]
Could you share your complete [[jas]] stanza?
Thanks.

**Comment by bellrichm** [comment]
And data/last24hours.js?

**Comment by gary-hammer** [comment]
As requested.
I have changed the stanza a couple of times when I thought it was some edit of mine that caused this. Which, could be if you can't reproduce it. Files in attached zip.


[gh-info.zip](https://github.com/bellrichm/weewx-jas/files/9945934/gh-info.zip)

**Comment by bellrichm** [comment]
I've looked at the changes in 2.3 and nothing jumps out at me, nor do any of the changes after it seem to fix it. So here we go..

Are you comfortable installing from this branch, https://github.com/bellrichm/weewx-jas/tree/bellrichm/issue66 ? If not, I can create a release.

There are a lot of changes after 2.3, so we are making a pretty big jump.  Sorry about that.

In this branch is some debug logging. It will fill your console. To turn it on set
```
        [[[Extras]]]
            jas_debug_level = 2
```
To turn it off, set `jas_debug_level = 3`

In theory this can done dynamically from the browser console via `setLogLevel(2)` and `setLogLevel(3)`

The logging in jas is something I just created based on the need to debug your issue. So, yeah, another thing changing and not fully tested.

I hope this isn't going to be too painful, we will see. As always, thanks for your help.
rich

**Comment by gary-hammer** [comment]
No idea how to get the install file from a given branch.
If you could roll a release I'd appreciate it.

**Comment by gary-hammer** [comment]
Same issues in browser console.
last24hours.js:134 Uncaught TypeError: Cannot read properties of undefined (reading 'mqtt')
    at last24hours.js:134:33
    at Array.forEach (<anonymous>)
    at handleMQTT (last24hours.js:125:22)
    at last24hours.js:635:29

**Comment by gary-hammer** [comment]
I have stripped the jas stanza down to fields that are absolutely in the mqtt stream as shown by mosquitto_sub
Still get the 'undefined' error

Plus, it reports that in the outtemp area of the website as shown in the attached pic.
![jas-issue66](https://user-images.githubusercontent.com/12861605/200203469-56f4c235-71f0-48aa-95fb-4e3901656cf2.png)

**Comment by bellrichm** [comment]
Oh, just created a release..l but you installed from the branch?
Did you set jas_debug_level?
Could you attach the latest javascript/last24hours.js?

**Comment by bellrichm** [comment]
Current theory, it has to do with you needing to rename the mqtt fields to weewx names.
I just committed a change based on this. Can you give it a try?

**Comment by gary-hammer** [comment]
Where do you mean rename the fields?
The fields are that when they are retrieved from the mosquitto server.
If I can/should create different names inside jas, I can certainly do that.

Or, would you like me to install the branch with the change?

**Comment by bellrichm** [comment]
Sorry for the confusion
‘ Current theory, it has to do with you needing to rename the mqtt fields to weewx names.’, was just some info.
2 requests
- install the latest from the branch
- Ensue that jas_debug_level is set to 2 in weewx.conf


Thanks!

**Comment by gary-hammer** [comment]
Ok, I installed with the commits and all is well.
Except the outside temp still alternates with undefined F with each MQTT update.
Zero errors in the console, just a slew of observations

**Comment by gary-hammer** [comment]
I set the debug level from the console and it seemed to take.
Shall I set it in weewx.conf instead?

**Comment by bellrichm** [comment]
No need to set via weewx.conf. 
You can turn logging back to 3.
I’ll look into the outTemp and let you know. 
Thanks for the help.

**Comment by bellrichm** [comment]
Oh, your latest javascript/last24hours.js would be appreciated. 
thanks

**Comment by gary-hammer** [comment]
One error in the console log:
echarts.min.js:35 z / z2 / zlevel of displayable is invalid, which may cause unexpected errors
Ce @ echarts.min.js:35

last 24 is attached.

[last24hours.txt](https://github.com/bellrichm/weewx-jas/files/9947621/last24hours.txt)

**Comment by gary-hammer** [comment]
Thanks Rich.
I'll wait on your findings.

**Comment by bellrichm** [comment]
‘ One error in the console log:
echarts.min.js:35 z / z2 / zlevel of displayable is invalid, which may cause unexpected errors
Ce @ echarts.min.js:35’
comes from echarts and doesn’t seem to ‘hurt’ anything…

just checking, we just need to fix the outTemp showing undefined?

**Comment by gary-hammer** [comment]
That's the only one that does me from deploying.
So, yes.

**Comment by bellrichm** [comment]
I changed what is logged to help debug the ‘undefined’ being displayed.  Could install from the branch and set the log level to 2?
Thanks

**Comment by gary-hammer** [comment]
I installed from the issue66 branch, I have log level 2 set in weewx.conf also tried setLogLevel(2) from the console.
Not sure if the weewx.conf has effect, but setting by the console gets an undefined entry in the log
Nothing except outTemp is being logged.

I'm attaching the console log. Around line 441 is when I tried setting log level.
[lts.lan-1667836634565.log](https://github.com/bellrichm/weewx-jas/files/9953353/lts.lan-1667836634565.log)

**Comment by gary-hammer** [comment]
Another data point.
Though I think I have max_decimals set for a number of observations, most are not respected.
Attaching the pertinent portion of the stanza.

[weewx.conf.txt](https://github.com/bellrichm/weewx-jas/files/9953543/weewx.conf.txt)

**Comment by bellrichm** [comment]
Interesting data point. I’m beginning to think that something in your mqtt data is confusing weewx-jas. Before I have you  install another version , could you run `jasShow(“test_obj”)` in the console?
Don’t worry about the `undefined`, I’m working on a workaround to display something else.

**Comment by gary-hammer** [comment]
This is what I get:

jasShow(“test_obj”)
VM38:1 Uncaught SyntaxError: Invalid or unexpected token

**Comment by gary-hammer** [comment]
You know. I'm thinking that as this is a test instance, I may wipe it and install weewx fresh. Add the driver I currently use. Add just this skin. See what it looks like.

There's been quite a lot installed/uninstalled and leftovers abound in the weewx.conf especially for drivers that I didn't uninstall, just reconfig for a new one.

BTW- on my Chromebook, all the decimal formatting is correct now. Still has the NaN though.

**Comment by bellrichm** [comment]
Your call on the restart. I’ll keep looking from my end. 
Let me know how it goes.

**Comment by gary-hammer** [comment]
I think I will do just that tomorrow.
So, until then, sure keep looking, but I will get a clean install done and let you know what I find.
What build would you like me to install tomorrow?

**Comment by bellrichm** [comment]
The branch does have an important fix, so let’s keep using it.

**Comment by gary-hammer** [comment]
Will do.

**Comment by gary-hammer** [comment]
Ok, I have wiped and reinstalled WeeWX, 
weewx-rtldavis to provide the Davis data (no inside temp or humidity)
weewx-mqtt to feed this machine's mosquitto server
MQTTSubscribeService for pressure (I don't use the temp this provides as it is in the basement)

Seasons skin is enabled for comparison purposes.
issue66 is installed of course. Well, the skin, hopefully not the issue.

I made change as I don't want inTemp so changed the user defined chart to cloudbase_foot
No MQTT enabled for the skin yet and it is fine. Every 5 minutes new page generated with correct values.

I'm attaching a snip of the current jas stanza from define an addition chart through current observations.
I'm also including what I'd like to do with the stanza. Look it over and let me know if you feel this should work.
If so, I'll make the edits and see what transpires. Just easier on a shiny new install to NOT make config changes again and again because of user error.

[clean-stanza.txt](https://github.com/bellrichm/weewx-jas/files/9960379/clean-stanza.txt)
[proposed-stanza.txt](https://github.com/bellrichm/weewx-jas/files/9960380/proposed-stanza.txt)

**Comment by gary-hammer** [comment]
This may be an easier solution for formatting the fields for those of us who use weewx-mqtt to get the loop data into mosquitto.

[weewx-mqtt formatting.txt](https://github.com/bellrichm/weewx-jas/files/9960451/weewx-mqtt.formatting.txt)

**Comment by bellrichm** [comment]
A couple requests,
Could you remove the `suffix =` statements. Support for this is going to be removed (hopefully temporarily). It shouldn’t matter… but it might
Could you capture data/last24hours.js an javascript/last24hours.js?
Could you update to latest from the branch? I wanted to cleanup the proposed debug logging.
Thanks

**Comment by gary-hammer** [comment]
Sorry 'suffix ='?
There's lots of something = in the file
What location(s) do you want?

**Comment by bellrichm** [comment]
Remove these suffix lines

                    [[[[[[barometer]]]]]]
                        suffix = ($trend.barometer.formatted)
                    [[[[[[windSpeed]]]]]]
                        suffix = $current.windDir.ordinal_compass ($current.windDir)

**Comment by gary-hammer** [comment]
I'll remove them, but they are commented out in my weewx.conf

**Comment by gary-hammer** [comment]
Ok, edits done and here is the result.
I'm attaching a zip with the files you asked for and a screenshot of the generated webpage.
MQTT is now updating the things it ought to be as far as I can tell.
[issue66-info.zip](https://github.com/bellrichm/weewx-jas/files/9961853/issue66-info.zip)

**Comment by bellrichm** [comment]
From your screenshot, looks like outTemp is still not correct…
I’m still working out how best to log/debug - sorry about that. I have updated the branch with my latest logging. This should be easier to save to a file. It also logs information on every mqtt message received.
`setLogLevel(1)` to get the detail logging, `setLogLevel(3)` to set to default. `getLogLevel()` to query current setting.

**Comment by gary-hammer** [comment]
Did you also note the missing/bad date on several of the Min/Max values?

**Comment by bellrichm** [comment]
Re: lack of logging 
I forgot that dev tools might be filtering debug/verbose level![image](https://user-images.githubusercontent.com/21961075/200644822-32a9aef4-d775-4b52-96f8-b45818bdd1b1.jpeg)

**Comment by gary-hammer** [comment]
Genius <g>.

Logs attached.
[lts.lan-1667933031900.log](https://github.com/bellrichm/weewx-jas/files/9964205/lts.lan-1667933031900.log)

**Comment by bellrichm** [comment]
This is telling me that outTemp is not in your MQTT payload… I’m working on handling that
last24hours.js:25 test_obj: {"dateTime":"1667933035.0","inTemp_F":"66.2983739454765","pressure_inHg":"30.031309685254843","usUnits":"1.0","altimeter_inHg":"30.477891260094157","maxSolarRad_Wpm2":"330.01768175662306","rainRate_inch_per_hour":"0.0","hourRain_in":"0.0","rain24_in":"0.0","dayRain_in":"0.0","windSpeed_mph":"4.0","windDir":"106.32806324110672","windBatteryStatus":"0.0"}

**Comment by gary-hammer** [comment]
Wonder where it went?
It is in the stanza where the websocket is defined:
 [[[[mqtt]]]]
                enable = True
                
                host = 10.10.100.15
                port = 9001
                
                useSSL = false
                
                username = weewx
                password = weewx
                
                topic = weather/loop
                [[[[[fields]]]]]
                    [[[[[[barometer_inHg]]]]]]
                        name = barometer
                    [[[[[[outHumidity]]]]]]
                        name = outHumidity
                    [[[[[[outTemp_F]]]]]]
                        name = outTemp
                    [[[[[[dewpoint_F]]]]]]
                        name = dewpoint
                    [[[[[[dayET]]]]]]
                        name = ET
                    [[[[[[heatindex_F]]]]]]
                        name = heatindex
                    [[[[[[windchill_F]]]]]]
                        name = windchill
                    [[[[[[appTemp_F]]]]]]
                        name = appTemp
                    [[[[[[windSpeed_mph]]]]]]
                        name = windSpeed
                    [[[[[[radiation_Wpm2]]]]]]
                        name = radiation
                    [[[[[[UV]]]]]]
                        name = UV
                    [[[[[[dayRain_in]]]]]]
                        name = rain
                    [[[[[[rainRate_inch_per_hour]]]]]]
                        name = rainRate

And it is in the mqtt loop data

![mqtt-lts](https://user-images.githubusercontent.com/12861605/200653385-722c2a70-db38-4911-a75e-481f72728b96.png)

**Comment by bellrichm** [comment]
Latest set of commits will not try to update UI if header observation is not in mqtt payload.
Also logs message.payloadString when message arrives. This is the earliest that weewx-jas has access to mqtt data.
Usual drill. Thanks

**Comment by gary-hammer** [comment]
That seems to have worked. I get a valid temp and it only changes when there is a new temp to report.
Logs attached.

[lts.lan-1667940222596.log](https://github.com/bellrichm/weewx-jas/files/9965085/lts.lan-1667940222596.log)

**Comment by bellrichm** [comment]
Awesome. From the latest log  I can see that some MQTT messages don’t have outTemp.
I’m pretty sure that a similar bug is with the other observations.

**Comment by bellrichm** [comment]
Just checked, the rest of the observations do NOT have this bug. 
Next up the min/max

**Comment by gary-hammer** [comment]
No, I haven't seen any other value experience this except outTemp.
I'm going to leave things as currently configured with the exception of setting max_decimals on most the observations.
Thanks Rich, it's been educational for me. At your service for further testing of course.

**Comment by bellrichm** [comment]
My plan is to push this branch to master and delete it.
I opened #76 for the min/max issue. After that is fixed I plan to publish a release.
Thanks again for all your help. I knew remote debugging was/is going to be a challenge. I think the logging code I developed and your help testin will make it much easier for the next person

**Comment by gary-hammer** [comment]
Thanks again Rich.
![tablet](https://user-images.githubusercontent.com/12861605/200709295-d440234e-f3db-463e-888c-917326868826.jpg)

**Comment by bellrichm** [comment]
Great screenshot. That is just the way I use it.

**Comment by bellrichm** [comment]
If min/max is still misbehaving, could you attach data/last24hours.js and javascript/last24hours.js to #76 
Extra credit for pages/last24hours.html and charts/last24hours.js. :)
