### ISSUE TITLE
Min/max displays ’NaN’ for the observation value and ‘invalid date’

### ISSUE THREAD

**Issue by bellrichm** [bellrichm/weewx-jas#76]

**Comment by gary-hammer** [comment]
I'm not certain it is going to be acting strange once I have at least 24hrs of data.
I dropped the entire weewx install .
I'll check first thing in the morning.

**Comment by bellrichm** [comment]
Agreed on the 24 hrs.
Thanks again

**Comment by bellrichm** [comment]
Current theory, I see null values in the misbehaving observations

**Comment by bellrichm** [comment]
the numerical value for null is 0 - Bingo
@gary-hammer I think I got it.

**Comment by gary-hammer** [comment]
Makes sense, there was a problem with null/0 a while back with a driver.
Can't remember the context though.

Good sleuthing!

**Comment by gary-hammer** [comment]
Attaching the files you requested. Might confirm your find.
[jas-minmax.zip](https://github.com/bellrichm/weewx-jas/files/9969574/jas-minmax.zip)

**Comment by gary-hammer** [comment]
Here's thought. When displaying the MQTT data, I specify websockets, port 9001
Looking at the ws stream weather/loop (and that is the key) several items never appear. Those are actually archive items.
It is also much different than the ws coming from my production server mosquitto.
The test server populates slowly, meaning that this or that value appears then more until all the fields are there.
The production server just pops up with all fields instantly.

I'm leaning towards the RTL source isn't the best test environment for this.
I can install a WLL driver if you'd like. It should act relatively the same as the Vantage driver on the production machine.

Pics for clarity.
mqtt-loop-only is what it says, loop only
mqtt-all is after the archive packet is included at the 5 minute mark
mqtt-vantage-loop is the production server

![mqtt-all](https://user-images.githubusercontent.com/12861605/200810181-e966f9a5-0811-42c4-8690-6a4a9df1e513.png)
![mqtt-loop-only](https://user-images.githubusercontent.com/12861605/200810184-5003437e-a816-4b42-ab2d-610e6921ace5.png)
![mqtt-vantage-loop](https://user-images.githubusercontent.com/12861605/200810185-bcdade08-2238-4037-8fb8-0f9f423a0105.png)

**Comment by gary-hammer** [comment]
This is what the WLL data looks like raw.
I think I'll install the driver and give it a whirl.

[wll-data.txt](https://github.com/bellrichm/weewx-jas/files/9970144/wll-data.txt)

**Comment by bellrichm** [comment]
It does sound like WLL driver will be closer to your production environment.
I’m actually glad your current test/dev environment has partial packets, it help to uncover a couple bugs.
I don’t have a WLL, so I use MQTTSubscribeDriver in my test/dev environments (with a modified method to publish) :)

**Comment by gary-hammer** [comment]
All is well after changing to the WLL driver.
No missing or invalid entries.

**Comment by bellrichm** [comment]
That’s great. Thanks for letting me know.
