### ISSUE TITLE
ET Value Carried Over From Previous Day (Current Conditions)

### ISSUE THREAD

**Issue by gary-hammer** [bellrichm/weewx-jas#83]
ET value looks like it is carried over from the previous day/24 hrs when displayed in current conditions.
See attached images.
Here is that portion of the stanza.

[[[[[[ET]]]]]]
     mqtt = false
     type = sum

![et-graph](https://user-images.githubusercontent.com/12861605/201162474-9fad497b-e85e-458d-bb4d-0a2d1e99e820.png)
![et-current](https://user-images.githubusercontent.com/12861605/201162475-698cdbb3-fee0-4a40-991e-71b4f4ab7538.png)

**Comment by bellrichm** [comment]
I’d sat this is working as (currently) designed. Each page has a time period. Observations that are summed in the current section are summed for that time period. Probably not what you want, but you could use the day page. But this will result in charts for the current day…
I attempted to write this up [here](https://github.com/bellrichm/weewx-jas/wiki)

**Comment by bellrichm** [comment]
I can understand where you are coming from. For me, I wanted all of the data to ‘align’. So, if I see a total rain fall of 2 inches in a table, when I scroll down the chart of rain fall will add to inches. Or vise versa, if I am looking at the chart of rain and it looks like a lot fell, I can easily scroll and see the total.
Totally personal preference…

**Comment by gary-hammer** [comment]
Makes sense, but confusing for me.
I'm flexible though.
