### ISSUE TITLE
0.3.0 Can't Change or Add Observations

### ISSUE THREAD

**Issue by gary-hammer** [bellrichm/weewx-jas#84]
Running into a problem that I can't solve.
I wanted to change a field and add a field in current observations.
Added the MQTT section, changed existing observation and added one.

Getting blank current observations for all  fields.

Attaching console log and the mqtt/observation portion of weewx,conf

[jas-console-01.txt](https://github.com/bellrichm/weewx-jas/files/9990880/jas-console-01.txt)
[new-stanza.txt](https://github.com/bellrichm/weewx-jas/files/9990881/new-stanza.txt)

**Comment by bellrichm** [comment]
Could you also attach the javascript/last24hours.js. Since the javascript is dynamically created, the file referenced in the console will usually be needed so that I can reference the line numbers.
In this case, setting the jas log level to 1 will probably help.

**Comment by gary-hammer** [comment]
Geez! Troubleshooting 101.  Erase the output directory when changes are made.
Sorry.
Working fine.

Standing by for the remnants of Nicole.
