### ISSUE TITLE
Update how wind max (and min) is calculated

### ISSUE THREAD

**Issue by bellrichm** [bellrichm/weewx-jas#87]
weewx-jas creates arrays of min and max values for the given time period (day, 24 hours, yesterday, week, etc.). It doe this to support the ‘zoom’ functionality. When ‘zoomed’ the min and max values are determined from the appropriate array slice.
To keep things simple/consistent, min and max arrays are created even when there is no aggregation. In this case the min, max, and average arrays are identical. 

Wind is a bit different from other observations. For some background information see, [http://weewx.com/docs/customizing.htm#Wind.](http://weewx.com/docs/customizing.htm#Wind) 

Under the covers when computing aggregate values in a series, WeeWX uses either windGust for max values or windSpeed for all other calculations. For additional information see, 
[https://github.com/weewx/weewx/blob/5cb78f8c6bf8c97a3d54af26edccc7964e5e9d9d/bin/weewx/xtypes.py#L300.](https://github.com/weewx/weewx/blob/5cb78f8c6bf8c97a3d54af26edccc7964e5e9d9d/bin/weewx/xtypes.py#L300)

The result is that wind can only be used with an aggregate value. In other words, which would you use to display wind, windGust or windSpeed? This means that WeeWX cannot create an array of wind values

**Comment by bellrichm** [comment]
There are a couple of options:
1. Use an aggregate_interval = archive_interval. This would result in something `$day.wind.series(time_series='start', aggregate_type='max', aggregate_interval=300, time_unit='unix_epoch_ms')`

Cons/challenges:
- Getting the archive_interval is not the easiest. This is the best I came up with.
 ```
 if generator.record is not None and 'interval' in generator.record:
      self.archive_interval = generator.record['interval'] * 60
else:
     self.archive_interval = to_int(generator.config_dict.get('StdArchive', {}).get('archive_interval', 300))
```
- A database query is performed for each array entry, 5 min * 12 intervals/hour * 24 hours = 1440 queries
2. Use the logic found here, https://github.com/weewx/weewx/blob/5cb78f8c6bf8c97a3d54af26edccc7964e5e9d9d/bin/weewx/xtypes.py#L300.
To create an array of wind max values, the windGust observation will be passed to WeeWX and output to a wind max array. 
To create an array of wind min values, the windSpeed observation will be passed to WeeWX and output to a wind min array. 

Cons:
- Hardcoded and a bit non-standard WeeWX code

**Comment by gary-hammer** [comment]
Why would these not work?

$day.windGust.max
$day.wind.max 
$day.windGust.maxtime
$day.wind.maxtime

**Comment by bellrichm** [comment]
> Why would these not work for the day's min/max?
> 
> $day.windGust.max $day.wind.max $day.windGust.maxtime $day.wind.maxtime

Only because that is not how weewx-jas calculates min/max. It finds min/max values from the an array of data for the time period. Yes, it could do it differently for day, last 24 hours, and yesterday; but I prefer to keep the code for all the time periods as similar as possible…

**Comment by gary-hammer** [comment]
Aaah.
That explains it.
